local Language = {}

Language.es = {
	--LoginSplash
	LSTitle = "ESTA POR COMENZAR,\nEL MEJOR VIAJE DE TU VIDA...",
	LSTitle2 = "CONOCE A TUS ANFITRIONES...",
	LSTitle3 = "CONOCE QUIEN SERÁ TU PRÓXIMO GUÍA  ",
	LSTitle4 = "CONVERSA CON ELLOS",
	LSSubTitle2 = "¿A dondé? ¿con que tipo de persona \nte gustaría conectarte?",
	LSSubTitle3 = "Navega entre las personas que cumplen con el perfil \nque Tu estas búscando y conoce más acerca de ellos.",
	LSSubTitle4 = "Abre una conversación privada con los usuarios \nque desees y conócelos más para definir \nquien te acompañara en tu próximo viaje.",
	LSBtnFace = "CONECTATE CON FACEBOOK",
	LSBtnNormal = "INGRESA CON: USUARIO Ó CORREO",
	LSBtnFree = "CONOCE MÁS SOBRE LA APLICACIÓN",
	LSTerms1 = "Al iniciar sesión usted está aceptando los",
	LSTerms2 = "términos y condiciones.",
	LSTermsTitle = "LICENSED APPLICATION END USER LICENSE AGREEMENT",
	--------------------------------------
	--LoginUserName
	LUNUser = "Usuario:",
	LUNEmail = "E-mail:",
	LUNPass = "Contraseña:",
	LUNRePass = "Re-Contraseña:",
	LUNRegistrar = "Registrarme:",
	LUNTerms1 = "Al iniciar sesión usted está aceptando los",
	LUNTerms2 = "términos y condiciones.",
	LUNBtnSignIn = "Acceder",
	LUNBtnRegister = "Nuevo Usuario",
	LUNTermsTitle = "LICENSED APPLICATION END USER LICENSE AGREEMENT",
	LUNEmptyFields = "Campos vacíos",
	LUNDifferentPass = "Contraseñas distintas",
	--------------------------------------
	--Welcome
	WCEnterCity = "Ingresa una ciudad",
	WCSearch = "Buscar",
	WCMoreFilters = "Más Filtros",
	WCSelectCity= "Seleccione una ciudad validad",
	--------------------------------------
	--Home
	HNoResultHome = "Busqueda \nsin resultados",
	HNoUserFound = "No se encontro usuarios",
	HYears = "Años",
	HUnregisteredResidence = "Residencia no registrada",
	HSeeProfile = "VER PERFIL",
	--------------------------------------
	--Profile
	PLikeToStart = "¿QUIERES CONVERSAR CON ",
	PSignUpNow = "¡Registrate ahora!",
	pConversationWith = "INICIAR CONVERSACIÓN",
	PYears = " Años",
	PCityNotAvailable = "Ciudad no disponible",
	PILiveIn = "Vive en ",
	PUnknown = "Desconocido",
	PIAmFrom = "Es de ",
	PSince = "Desde hace ",
	POffersAccommodation = "Ofreco Alojamiento",
	PYes = "Si",
	PNo = "No",
	PCar = "Vehiculo Propio",
	PFood = "Comida",
	PAny = "Ninguno",
	PLanguages = "Idiomas",
	PHobbies = "Hobbies",
	PLevelOfEducation = "Nivel de estudio",
	PProfessionalTraining = "Formacion profesional",
	PWorkingArea = "Area laboral",
	PFreelance = "Por Cuenta Propia",
	PEmployee = "Por cuenta ajena",
	PPets = "mascota",
	PHas = "Tiene ",
	PSports = "Deportes",
	PSportYouPlay = "Practica deporte",
	PYouPlay = "Practica ",
	PYouSmok = "Fumas",
	PYouDrinkAlcohol = "Bebes",
	PYouPsychotropicDrugs = "Psicotropicos",	
	--------------------------------------
	--MyProfile
	MpSaveChanges = "Guardar Cambios",
	MpYears = " Años",
	MpDateOfBirth = "Seleccione una fecha de nacimiento",
	MpName = "Nombre: ",
	MpLastName = "Apellidos: ",
	MpGender = "Genero ",
	MpCountryOrigin = "Pais de origen: ",
	MpResidence = "Residencia: ",
	MpTimeLiving = "Tiempo de \nresidencia: ",
	MpEmail = "Email: ",
	MpSelect = "Seleccionar",
	MpAccommodation = "Alojamiento: ",
	MpVehicle = "Vehiculo: ",
	MpFood = "Comida: ",
	MpAny = "Ninguno",
	MpYes = "Si",
	MpNo = "No",
	MpLanguages = "Idiomas: ",
	MpHobbies = "Hobbies: ",
	MpLevelOfEducation = "Nivel de estudio: ",
	MpProfessionalTraining = "Formacion profesional: ",
	MpWorkingArea = "Area laboral: ",
	MpFreelance = "Por Cuenta Propia: ",
	MpEmployee = "Por cuenta ajena: ",
	MpPets = "mascota: ",
	MpSportYouPlay = "Practica deporte: ",
	MpYouSmok = "Fumas: ",
	MpYouDrinkAlcohol = "Bebes: ",
	MpYouPsychotropicDrugs = "Psicotropicos: ",
	MpNoLanguage = "No cuenta con ningun idioma",
	MpOtherLanguages = "Tus Idiomas",
	MpNoSport = "No cuenta con ningun deporte",
	MpSportThatYouPlay = "Deportes que practicas",
	MpEditHobbies = "Editar pasatiempos",
	MpYourHobbies = "Tus hobbies",
	MpOk = "Aceptar",
	
	
}

Language.en = {
	--LoginSplash
	LSTitle = "YOU ARE ABOUT TO BEGIN, THE BEST TRIP OF YOUR LIFE...",
	LSTitle2 = "MEET YOUR HOSTES...",
	LSTitle3 = "MEET YOUR NEXT GUIDE ",
	LSTitle4 = "TALK TO THEM",
	LSSubTitle2 = "Where? What type of people would you like to connect with?",
	LSSubTitle3 = "Navega entre las personas que cumplen con el perfil \nque Tu estas búscando y conoce más acerca de ellos.",
	LSSubTitle4 = "Navigate among the people meeting the profile you´re looking for and learn more about them.",
	LSBtnFace = "CONNECT WITH FACEBOOK",
	LSBtnNormal = "LOG IN: USER OR E-MAIL",
	LSBtnFree = "KNOW MORE ABOUT THE APP",
	LSTerms1 = "Al iniciar sesión usted está aceptando los",
	LSTerms2 = "términos y condiciones.",
	LSTermsTitle = "LICENSED APPLICATION END USER LICENSE AGREEMENT",
	--------------------------------------
	--LoginUserName
	LUNUser = "User:",
	LUNEmail = "E-mail:",
	LUNPass = "Password:",
	LUNRePass = "Re-passwords:",
	LUNRegistrar = "Sign up:",
	LUNTerms1 = "Al iniciar sesión usted está aceptando los",
	LUNTerms2 = "términos y condiciones.",
	LUNBtnSignIn = "Log in",
	LUNBtnRegister = "Nuevo Usuario",--
	LUNTermsTitle = "LICENSED APPLICATION END USER LICENSE AGREEMENT",
	LUNEmptyFields = "Empty fields",
	LUNDifferentPass = "Different passwords",
	--------------------------------------
	--Welcome
	WCEnterCity = "Enter city",
	WCSearch = "Search",
	WCMoreFilters = "More filters",
	WCSelectCity= "Seleccione una ciudad validad",
	--------------------------------------
	--Home
	HNoResultHome = "Busqueda \nsin resultados",
	HNoUserFound = "No user was found",
	HYears = "Years",
	HUnregisteredResidence = "Residencia no registrada",
	HSeeProfile = "SEE PROFILE",
	--------------------------------------
	--Profile
	PLikeToStart = "WOULD YOU LIKE TO START A ",
	PSignUpNow = "Sign up now!",
	pConversationWith = "CONVERSATION WITH",
	PYears = " Years",
	PCityNotAvailable = "City not available",
	PILiveIn = "I live in ",
	PUnknown = "Unknown",
	PIAmFrom = "I am from ",
	PSince = "Since ",
	PSince = "Desde hace ",
	POffersAccommodation = "Offers accommodation",
	PYes = "Yes",
	PNo = "No",
	PCar = "Car",
	PFood = "Food",
	PAny = "Any",
	PLanguages = "Languages",
	PHobbies = "Hobbies",
	PLevelOfEducation = "Level of education",
	PProfessionalTraining = "Professional training",
	PWorkingArea = "Working area",
	PFreelance = "Freelance",
	PEmployee = "Employee",
	PPets = "pets",
	PHas = "Has ",
	PSports = "Sports",
	PSportYouPlay = "Sports you play",
	PYouPlay = "I play ",
	PYouSmoke = "Do you smoke",
	PYouDrinkAlcohol = "Do you drink alcohol",
	PYouPsychotropicDrugs = "Do you take psychotropic drugs",
	--------------------------------------
	--MyProfile
	MpSaveChanges = "Save changes",
	MpYears = " Years",
	MpDateOfBirth = "Select a date of birth",
	MpName = "Name: ",
	MpLastName = "Last name: ",
	MpGender = "Gender: ",
	MpCountryOrigin = "Country of origin: ",
	MpResidence = "Residence: ",
	MpTimeLiving = "Time living\nthere: ",
	MpEmail = "E-mail: ",
	MpSelect = "Select",
	MpAccommodation = "Accommodation: ",
	MpVehicle = "Vehicle: ",
	MpFood = "Food: ",
	MpAny = "Any",
	MpYes = "Yea",
	MpNo = "No",
	MpLanguages = "Languages: ",
	MpHobbies = "Hobbies: ",
	MpLevelOfEducation = "Level of education: ",
	MpProfessionalTraining = "Professional training: ",
	MpWorkingArea = "Working area: ",
	MpFreelance = "Freelance: ",
	MpEmployee = "Employee: ",
	MpPets = "Pets: ",
	MpSportYouPlay = "Sports you play: ",
	MpYouSmok = "Do you smoke: ",
	MpYouDrinkAlcohol = "Do you drink alcohol: ",
	MpYouPsychotropicDrugs = "Do you take psychotropic drugs: ",
	MpNoLanguage = "No language has been selected",
	MpOtherLanguages = "Other languages",
	MpNoSport = "No sport has been selected",
	MpSportThatYouPlay = "Sports that you play",
	MpEditHobbies = "Edit hobbies",
	MpYourHobbies = "Your hobbies",
	MpOk = "Ok",
}

return Language